[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers = 
    ui: Маркировка для запуска UI автотестов.
    smoke: Маркировка для смоук автотестов.
    regression: Маркировка для регрессионных тестов.
    courses: Маркировка для запуска тестов страницы /courses
    slow: Маркировка для медленных тестов.
    critical: Маркировка для критических тестов.
    registration: Маркировка для регистрационных тестов.
    authorization: Маркировка для авторизационных тестов.